// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: domain.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Domain {

  /// <summary>Holder for reflection information generated from domain.proto</summary>
  public static partial class DomainReflection {

    #region Descriptor
    /// <summary>File descriptor for domain.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static DomainReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cgxkb21haW4ucHJvdG8SBkRvbWFpbio7CgxUcmFmZmljTGlnaHQSCwoHVW5r",
            "bm93bhAAEgcKA1JlZBABEgoKBlllbGxvdxACEgkKBUdyZWVuEANiBnByb3Rv",
            "Mw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Domain.TrafficLight), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum TrafficLight {
    [pbr::OriginalName("Unknown")] Unknown = 0,
    [pbr::OriginalName("Red")] Red = 1,
    [pbr::OriginalName("Yellow")] Yellow = 2,
    [pbr::OriginalName("Green")] Green = 3,
  }

  #endregion

}

#endregion Designer generated code
